### ISSUE TITLE
after installing this add-on Anki can't be started

### ISSUE THREAD

**Issue by ijgnd** [Arthur-Milchior/anki-template-card-type#1]
thank you for sharing this add-on.

I downloaded from ankiweb (version 2019-01-12) as the only add-on into the most recent version of Anki (2.1.8) on linux.

After installing your add-on I can't start Anki - Anki closes itself. This is the output I have on the commandline.

    ImportError: cannot import name 'templates'
        from . import templates
    File "/home/ijgnd/.local/share/Anki2/addons21/1159566613/init.py", line 11, in <module>
    Traceback (most recent call last):

the add-on downloaded from ankiweb does not contain any subfolders. 

In your repo you have a file "zipping". I ran the command it contains on linux. On my machine this command creates a zip file that does not contain the full folders with their content but it only creates empty folders. and maybe ankiweb removes empty subfolders?

----

I downloaded the latest version from github as of commit 780dcef. I don't know if I'm supposed to run this directly. But when I try to Anki doesn't start and I get this message:

    TypeError: __init__() got an unexpected keyword argument 'caption'
        super().__init__(**kwargs)
    File "/home/ijgnd/.local/share/Anki2/addons21/1159566613/generators/generators.py", line 710, in __init__
        super().__init__(toKeep = toKeep, **kwargs)
    File "/home/ijgnd/.local/share/Anki2/addons21/1159566613/generators/generators.py", line 766, in __init__
        super().__init__(child = child, **kwargs)
    File "/home/ijgnd/.local/share/Anki2/addons21/1159566613/generators/html/html.py", line 19, in __init__
        ret=HTML(tag = "table", child = lines, attrs = attrs, caption=label)
    File "/home/ijgnd/.local/share/Anki2/addons21/1159566613/generators/questions/listFields.py", line 158, in globalFun
        ret = self.globalFun(elements)
    File "/home/ijgnd/.local/share/Anki2/addons21/1159566613/generators/questions/listFields.py", line 79, in __init__
        super().__init__(self.fields, localFun = localFun, globalFun = globalFun, name = name,**kwargs)
    File "/home/ijgnd/.local/share/Anki2/addons21/1159566613/generators/questions/listFields.py", line 160, in __init__
        "◁",
    File "/home/ijgnd/.local/share/Anki2/addons21/1159566613/examples/algebra/algebra.py", line 228, in <module>
        from .algebra.algebra import algebra
    File "/home/ijgnd/.local/share/Anki2/addons21/1159566613/examples/imports.py", line 1, in <module>
        from ..examples.imports import *
    File "/home/ijgnd/.local/share/Anki2/addons21/1159566613/user_files/imports.py", line 7, in <module>
        from .user_files.imports import *
    File "/home/ijgnd/.local/share/Anki2/addons21/1159566613/imports.py", line 12, in <module>
        from ..imports import *
    File "/home/ijgnd/.local/share/Anki2/addons21/1159566613/templates/evaluate.py", line 4, in <module>
        from . import evaluate
    File "/home/ijgnd/.local/share/Anki2/addons21/1159566613/templates/__init__.py", line 1, in <module>
        from . import templates
    File "/home/ijgnd/.local/share/Anki2/addons21/1159566613/init.py", line 11, in <module>

**Comment by Arthur-Milchior** [comment]
Hi

Thank you for the feedback.
Zipping is not supposed to be run, except by me. It's the command which zip the files so that I can upload them. I'll get a look at it later today

**Comment by Arthur-Milchior** [comment]
Add-on is updated. I downloaded it and it seems to work now.

My mistake was quite simple. I forgot to include the content of the folder in the zip, so a lot of code was missing.

**Comment by ijgnd** [comment]
thanks.
